# Generated by Django 3.0.4 on 2020-06-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='metadata',
            field=models.ManyToManyField(blank=True, to='content_management.Metadata'),
        ),
    ]
