# Generated by Django 3.0.4 on 2020-07-17 12:36

import content_management.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0003_remove_content_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='filesize',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_file',
            field=models.FileField(max_length=300, upload_to='contents/', validators=[content_management.validators.validate_unique_filename, content_management.validators.validate_unique_file], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
