# Generated by Django 3.0.4 on 2020-07-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0004_auto_20200717_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='reviewed_on',
            field=models.DateField(null=True),
        ),
    ]
