# Generated by Django 3.0.4 on 2020-08-25 18:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0006_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryversion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='content_management.User'),
        ),
        migrations.AddField(
            model_name='libraryversion',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
