# Generated by Django 3.0.4 on 2020-09-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0007_auto_20200825_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='duplicatable',
            field=models.BooleanField(default=0),
        ),
    ]
