# Generated by Django 3.0.4 on 2021-02-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0013_auto_20210209_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='copyright',
            new_name='copyright_notes',
        ),
        migrations.RemoveField(
            model_name='libraryfolder',
            name='banner_img',
        ),
        migrations.AddField(
            model_name='content',
            name='copyright_site',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='liblayoutimage',
            name='image_group',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Logo'), (2, 'Banner')], default=1),
        ),
        migrations.AlterField(
            model_name='libraryversion',
            name='version_number',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
