# Generated by Django 3.0.4 on 2021-02-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0014_auto_20210219_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryversion',
            name='version_number',
            field=models.CharField(max_length=300),
        ),
    ]
