# Generated by Django 3.0.4 on 2021-03-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0016_auto_20210226_1718'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='libraryversion',
            name='unique name and number',
        ),
        migrations.AlterField(
            model_name='libraryversion',
            name='version_number',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
