# Generated by Django 3.0.4 on 2021-04-09 16:25

from django.db import migrations, models

import content_management.models
import content_management.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('content_management', '0017_auto_20210323_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='file_name',
            field=models.CharField(default="", max_length=500, unique=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='content',
            name='copyright_site',
        ),
        migrations.RemoveField(
            model_name='content',
            name='original_source',
        ),
        migrations.AlterField(
            model_name='content',
            name='content_file',
            field=models.FileField(max_length=500, upload_to=content_management.models.Content.set_file_name,
                                   validators=[content_management.validators.validate_unique_filename,
                                               content_management.validators.validate_unique_file],
                                   verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
