# Generated by Django 3.0.4 on 2021-04-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0019_auto_20210409_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
