# Generated by Django 3.0.4 on 2021-04-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0020_auto_20210414_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='copyright_notes',
            field=models.TextField(null=True),
        ),
    ]
