# Generated by Django 3.0.4 on 2021-04-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0021_auto_20210416_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
